[platformio]
default_envs = esp32dev_debug

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_deps =
  adafruit/Adafruit BusIO @ ^1.17.0
  arduino-libraries/Arduino_CRC32 @ ^1.0.0
  https://github.com/bitcoin-ring/Adafruit-PN532-NTAG424.git

build_flags =
  -DCORE_DEBUG_LEVEL=0
  O
monitor_filters =
  time

[env:esp32dev_debug]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_type = debug

lib_deps =
  adafruit/Adafruit BusIO @ ^1.17.0
  arduino-libraries/Arduino_CRC32 @ ^1.0.0
  https://github.com/bitcoin-ring/Adafruit-PN532-NTAG424.git

build_flags =
  -DCORE_DEBUG_LEVEL=5

monitor_filters =
  time
